/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CodeChallenge401;

public class ArrayShift {
    public int[] arrayShift(int[] inputArray, int numToInsert){

        int[] result = new int[inputArray.length + 1];
        int mid;
        int odd = inputArray.length % 2;

        if(inputArray.length == 0){
            return new int[]{numToInsert};
        }
        else if( inputArray.length == 1){
            result = new int[]{inputArray[0], numToInsert};
            return result;
        }

        if((inputArray.length % 2) == 0){
            mid = (inputArray.length / 2);
        }
        else{
            mid = (inputArray.length + 1) /2;
        }

        for(int i = 0; i < result.length; i++){
            if(i < mid ){
                result[i] = inputArray[i];
            } else if (i == mid){
                result[mid] = numToInsert;
            } else {
                result[i] = inputArray[i - 1];
            }
        }
        return result;
    }
}